In [7]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, recall_score,make_scorer
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron

import numpy as np
pd.set_option('display.max_columns', None)


In [8]:
final_data_df = pd.read_csv('final_data.csv')

X = final_data_df.drop(columns=['accepted']).copy()
y = final_data_df['accepted'].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=13)

final_data_df.head()

discussions_count  comments_count  movie_count  screenshot_count  \
0          -0.299559        0.387851            0                 6   
1          -0.299559       -0.119405            0                 4   
2          -0.299559        0.761618            0                 2   
3          -0.299559        0.757168            0                 8   
4           0.320877        3.142160            0                 0   

   awards_count  link_count  file_size_mb  change_notes  certified_compatible  \
0             0           0         4.971             7                     1   
1             0           0         2.958             4                     1   
2             0           0         4.277             1                     0   
3             0           0         4.567             3                     0   
4             0           0         0.572             1                     0   

   creator_count  featured_collection_count  visitors_count  favorites_count  \
0              2                        115       -0.003128              428   
1              2                         46       -0.261479              173   
2              4                        100        0.502919              859   
3              2                         91        0.359304              650   
4              1                         17        2.183300              102   

   accepted  is_medal  posted_time  updated_time  passed_time  media_count  \
0         1         0            0             4            3            6   
1         1         0            0             3            2            4   
2         1         0            0             0            0            2   
3         1         0            0             0            0            8   
4         1         0            0             0            0            0   

   class_count  item_slot_count  submitted_by_submitter  class_scout  \
0            5                1                     380            1   
1            1                1                     380            1   
2            1                1                     153            0   
3            9                1                     114            1   
4            0                1                       1            0   

   class_soldier  class_pyro  class_demoman  class_heavy  class_engineer  \
0              0           0              1            1               1   
1              0           0              0            0               0   
2              0           0              0            0               0   
3              1           1              1            1               1   
4              0           0              0            0               0   

   class_medic  class_sniper  class_spy  item_slot_headgear  item_slot_misc  \
0            0             1          0                   0               1   
1            0             0          0                   0               1   
2            0             0          1                   0               1   
3            1             1          1                   0               1   
4            0             0          0                   0               1   

   item_slot_taunt  item_slot_weapon        v1      v2       v3         v4  \
0                0                 0  0.268692  154.00   5492.0  35.432258   
1                0                 0  0.265896   40.00   2218.0  54.097561   
2                0                 0  0.116414  238.00  11905.0  49.811715   
3                0                 0  0.140000  237.00  10085.0  42.373950   
4                0                 0  0.166667  193.25   8300.0  42.894057   

         v5  
0  0.857143  
1  0.800000  
2  0.666667  
3  0.888889  
4  0.000000

In [13]:
lg1 = LogisticRegression(max_iter=10000000, random_state=13,class_weight={0: 1, 1: 4})
lg1.fit(X_train, y_train)

y_pred = lg1.predict(X_test)

print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')
print(f'F1 score: {f1_score(y_test,y_pred)}')

Confusion Matrix: 
[[5803  294]
 [ 207  326]]
Accuracy Score: 0.9244343891402715
Recall score: 0.6116322701688556
F1 score: 0.5654813529921943


g:\python\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
tree = DecisionTreeClassifier(class_weight={0:1,1:4},random_state=42)
tree_grid = GridSearchCV(tree, dict(max_depth=range(2,20,2),min_samples_split=range(2,30,2)), scoring=make_scorer(f1_score),n_jobs=-1)
tree_grid.fit(X_train, y_train)

print(tree_grid.best_params_)
print(tree_grid.best_score_)

y_pred = tree_grid.predict(X_test)

print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')
print(f'F1 score: {f1_score(y_test,y_pred)}')

{'max_depth': 10, 'min_samples_split': 2}
0.6242928938069578
Confusion Matrix: 
[[5807  290]
 [ 173  360]]
Accuracy Score: 0.9301659125188537
Recall score: 0.6754221388367729
F1 score: 0.6086221470836856


In [11]:
rand_forest = RandomForestClassifier(class_weight={0:1,1:4},random_state=42)
rand_forest_grid = GridSearchCV(rand_forest, dict(n_estimators=range(3,70,3)), scoring=make_scorer(f1_score),n_jobs=-1)
rand_forest_grid.fit(X_train, y_train)

print(rand_forest_grid.best_params_)
print(rand_forest_grid.best_score_)

y_pred = rand_forest_grid.predict(X_test)

print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')
print(f'F1 score: {f1_score(y_test,y_pred)}')

{'n_estimators': 27}
0.6402827969695835
Confusion Matrix: 
[[6071   26]
 [ 266  267]]
Accuracy Score: 0.9559577677224737
Recall score: 0.50093808630394
F1 score: 0.6464891041162227
